language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install  --dev --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover=tests/build/logs/clover.xml

after_script:
  - ./vendor/bin/test-reporter --coverage-report=tests/build/logs/clover.xml --stdout > codeclimate.json
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/build/logs/clover.xml
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

addons:
    code_climate:
        repo_token:
            secure: "dx8HKHvruf10bh7FrhRfCUqdqxjbL4Rn/dOS7Hvhw9IkYY7iHxADckLTIrQMqVC0al7ukvCsQpFwB6iVEhUvcHKtvFATnwmv1yvpatgvHjNtKEXCuDaLxVTuhUgP71teFYXKi6CK42cVdq1UJAEdFyAdTLBs+KDCtqtzucRf3Tk="
